/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        // MD3 color tokens (from Stitch design system)
        'primary': '#003331',
        'on-primary': '#ffffff',
        'primary-container': '#004b49',
        'on-primary-container': '#7ebab7',
        'primary-fixed': '#b1eeea',
        'primary-fixed-dim': '#95d1ce',
        'on-primary-fixed': '#00201f',
        'on-primary-fixed-variant': '#084f4d',
        'inverse-primary': '#95d1ce',
        'surface-tint': '#2a6865',
        'secondary': '#4a6360',
        'on-secondary': '#ffffff',
        'secondary-container': '#cae5e1',
        'on-secondary-container': '#4e6764',
        'secondary-fixed': '#cde8e4',
        'secondary-fixed-dim': '#b1ccc8',
        'on-secondary-fixed': '#051f1d',
        'on-secondary-fixed-variant': '#334b49',
        'tertiary': '#49220a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#64371e',
        'on-tertiary-container': '#e1a181',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#fab896',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#693b22',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f8f9fa',
        'on-surface': '#191c1d',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#3f4948',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
        'outline': '#707978',
        'outline-variant': '#bfc8c7',
        // Keep legacy scale for any old class references
        'primary-scale': {
          50: '#e8f5f0',
          100: '#c8e6dd',
          200: '#9fd5c8',
          300: '#6bbfb0',
          400: '#3da89a',
          500: '#1d9185',
          600: '#0d7a6f',
          700: '#006358',
          800: '#004d44',
          900: '#003d36',
          950: '#003331',
        },
      },
      fontFamily: {
        sans: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Manrope', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
